#!/bin/bash
# Author: Joshua Chen
# Date: 2015-11-14
# Location: Shenzhen
# Desc: a git authentication program uses gpg to secure credentials.

# read protocol and host from stdin
read_stdin() {
    :
}

# encrypt with gpg
enc() {
    :
}

# decrypt with gpg
dec() {
    :
}

# find encrypted file that matches the given protocol and host
find_ent() {
    :
}

datadir="$HOME/.git-credential-gpg"
index="$datadir/index"

mkdir -p "$datadir"
touch "$index"
