#!/bin/bash
# Author: Joshua Chen
# Date: 2015-11-14
# Location: Shenzhen
# Desc: a git authentication program uses gpg to secure credentials.

# read protocol and host from stdin, return true if both
# are provided, otherwise false. We shall at least have a
# protocol and a host variable when success, and a username
# and password on store mode.
read_stdin() {
    :
}

# encrypt the data from stdin with gpg, write it to stdout
enc() {
    :
}

# decrypt the data from stdin with gpg, write it to stdout
dec() {
    :
}

# find encrypted file that matches the given protocol and host
find_ent() {
    :
}

datadir="$HOME/.git-credential-gpg"
index="$datadir/index"

mkdir -p "$datadir"
touch "$index"
